openapi: 3.0.0
info:
  title: roster-service
  version: '1.0'
  description: 'API responsible for adding, modifying, leaving, and fetching Driver Roster data.'
servers:
  - url: 'http://localhost:8001'
    description: External
  - url: 'http://roster-service:8000'
    description: Internal
paths:
  /roster:
    get:
      summary: get-roster
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - username
                    - name
                    - rate
                  properties:
                    username:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                    rate:
                      type: number
      operationId: get-roster
      description: Fetch list of all drivers currently in the Roster.
    post:
      summary: ''
      operationId: join-roster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  username:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  rate:
                    type: number
                required:
                  - username
                  - name
                  - rate
              examples:
                example-1:
                  value:
                    username: babydriver
                    name: Ansel Elgort
                    rate: 15
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Request is missing JWT token or rate
                example-2:
                  value:
                    error: User is already in roster
                example-3:
                  value:
                    error: Invalid rate value supplied
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Invalid JWT token
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Parsing request to join roster failed
      description: Adds a driver with a valid JWT to the Roster
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                token:
                  type: string
                  minLength: 1
                rate:
                  type: integer
              required:
                - token
                - rate
            examples:
              example-1:
                value:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJuYW1lIjoiIiwiZXhwIjoxNjE1NTAyNTgwfQ.-Y0YwMjO8O2rpXNZswSt4NzpiYuca1QQ1M-dLOSdy6M
                  rate: 5
    put:
      summary: ''
      operationId: update-roster
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  username:
                    type: string
                    minLength: 1
                  name:
                    type: string
                    minLength: 1
                  rate:
                    type: number
                required:
                  - username
                  - name
                  - rate
              examples:
                example-1:
                  value:
                    username: babydriver
                    name: Ansel Elgort
                    rate: 15
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Request is missing JWT token or rate
                example-2:
                  value:
                    error: User is not in roster
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Invalid JWT token
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Parsing request to update roster rate failed
      description: Updates a driver's rate/km
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                token:
                  type: string
                  minLength: 1
                rate:
                  type: number
              required:
                - token
                - rate
            examples:
              example-1:
                value:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJuYW1lIjoiIiwiZXhwIjoxNjE1NTAyNTgwfQ.-Y0YwMjO8O2rpXNZswSt4NzpiYuca1QQ1M-dLOSdy6M
                  rate: 5
    delete:
      summary: ''
      operationId: leave-roster
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Request is missing JWT token
                example-2:
                  value:
                    error: User is not in roster
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Invalid JWT Token
        '500':
          description: Internal Server Error
          headers: {}
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  error:
                    type: string
                    minLength: 1
                required:
                  - error
              examples:
                example-1:
                  value:
                    error: Parsing request ot leave roster failed
      description: Removes a driver from the roster
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                token:
                  type: string
                  minLength: 1
              required:
                - token
            examples:
              example-1:
                value:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhYnlkcml2ZXIiLCJuYW1lIjoiIiwiZXhwIjoxNjE1NTUxNjk0fQ.3HzpCbk9IvIbegmxmSb9zOropk_VOt8DRI63YStiPJc
components:
  schemas: {}
